### PR TITLE
Update to riot 2.4.1

### PR DESCRIPTION
**Pull request by u007**

### CODE REVIEW

**Comment by brauliobo** [comment]
thanks @u007 can you create another PR just with the rails 5 change?

also, please use the vanilla riot 2.4.1 and squash update commits into one

**Comment by u007** [comment]
updated to vanilla

**Comment by u007** [comment]
sorry i don't know how to squash it , how do i revert remote push

**Comment by brauliobo** [comment]
@u007 please remove the rails 5 commit and squash the others into one to reduce the noise

**Comment by u007** [comment]
is this good?

**Comment by brauliobo** [comment]
actually I expect everything in one commit only with the update. please see http://stackoverflow.com/questions/5189560/squash-my-last-x-commits-together-using-git/28789349#28789349 and then `push -f`. Or I can cherry pick only the necessary update if you prefer

**Comment by u007** [comment]
i think do a cherry pick, then i will delete my repo after u have merged with rails 5 update as well

**Comment by brauliobo** [comment]
ok @u007 the final result of this PR should be only one commit with the update to riot 2.4.1

**Comment by brauliobo** [comment]
cherry picked @ https://github.com/bjarosze/riot_js-rails/commit/929253aed8c0698c24151d2c32ca5ea7af8914d8

**Pull request closed without merging**
